name: Development workflow

on:
  push:
    branches:
      - 'development'
      - 'feature/**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Run Unit tests
        run: bash ./gradlew test

  lint:
    name: Run lints
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Run Lints
        run: bash ./gradlew lintDebug
      - uses: actions/upload-artifact@v1
        with:
          name: Lint results
          path: app/build/reports/lint-results-debug.html

  ui_tests:
    name: Run UI Tests
    runs-on: macOS-latest
    needs:
      - test
      - lint
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Run UI Tests Locally
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck