name: Master workflow

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Assemble APK
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Assemble Debug Version
        run: bash ./gradlew assembleDebug
      - name: Upload Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  firebase_publish:
    name: Publish on Firebase App Distribution
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: |
            appdistribution:distribute app-debug/app-debug.apk \
              --app ${{ secrets.FIREBASE_APP_ID }} \
              --groups "testers"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}