name: Pull request to master workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build APKs for UI Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Assemble Debug Version
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Assemble Android Instrumentation Tests
        run: bash ./gradlew assembleDebugAndroidTest
      - name: Upload Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase_ui:
    name: Run UI Tests in Firbase Test Lab
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Download app APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug
      - name: Download Android Test APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest
      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
      - name: Run UI in Firebase Test Lab
        run: | 
          gcloud firebase test android run \
            --type instrumentation \
            --app app-debug/app-debug.apk \
            --test app-debug-androidTest/app-debug-androidTest.apk \
            --device model=Pixel2,version=28,locale=ru,orientation=portrait
